version: "3"
services:
  cm:
    build:
      context: ./cm
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    external_links:
         - rabbit
    networks:
         - hotmaps-toolbox-service_cm-net
networks:
 hotmaps-toolbox-service_cm-net:
   external: true




